# Generated by Django 4.2.24 on 2025-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
