# Generated by Django 4.2.24 on 2025-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_favorite_recipe_alter_favorite_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                max_length=32,
                unique=True,
                verbose_name="Slug тега",
            ),
            preserve_default=False,
        ),
    ]
