# Generated by Django 4.2.24 on 2025-09-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
